services:
  r-dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/rstudio/project:cached
    environment:
      - USER=rstudio
      - PASSWORD=password
    ports:
      - "8787:8787"
