services:
  r-dev-env:
    container_name: r-dev-container
    image: r-dev-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_CLI: "true"
    volumes:
      - ..:/home/rstudio/project:cached
    environment:
      - USER=rstudio
      - PASSWORD=password
    ports:
      - "8787:8787"
